
-- CREATING OF STUDENTS TABLE

create table students(
	STUDENT_ID VARCHAR(100) PRIMARY KEY,
	STUDENT_NAME VARCHAR(100),
	EMAIL VARCHAR(100),
	PHONE NUMBER(20),
	DOB VARCHAR(100),
	COURSE_ID VARCHAR(100),
	GENDER VARCHAR(100),
	ADDRESS VARCHAR(100)
);

desc students;

--TO VIEW ALL THE COLUMNS AND THE VALUES IN YOUR TABLE
select * from students;


    -- SELECTING A SPECIFIC COLUMNS FROM THE STUDENTS TABLE
    SELECT student_name, email, phone, marks from students;
    
    
--  CHANGING OF COLUMN NAME
ALTER TABLE students
RENAME COLUMN DOB TO DATE_OF_BIRTH;

ALTER TABLE STUDENTS
RENAME COLUMN COURSE TO COURSE_ID;

-- ADDING A COLUMN TO TABLE
alter table students
add (REG_DATE VARCHAR(100));

alter table students
add (STUDY_TYPE VARCHAR(100));	

-- DROPING A COLUMN
Alter table students
drop column STUDY_TYPE;



		--  UPDATE A SINGLE COLUMN

		update students set date_of_birth = '2000-01-01' where id = 3;
		


-- CHANGING A SINGLE RECORD
UPDATE STUDENTS
SET COURSE_ID = 'CYBER4.2'
WHERE student_id = 'CYBERMO23';

UPDATE STUDENTS
SET ADDRESS = 'WA'
WHERE student_id = 'CSDM002';


-- SELECTING A SINGLE RECORD FROM STUDENT TABLE
SELECT * FROM STUDENTS
WHERE student_id = 'CYBERMO23';
		

--  DROPPING A TABLE
DROP TABLE students;


--  INSERTING RECORDS INTO STUDENTS TABLE
insert into students(STUDENT_ID, STUDENT_NAME, EMAIL, PHONE, DATE_OF_BIRTH, COURSE_ID, GENDER, ADDRESS, REG_DATE) VALUES('CSDM002', 'KENNEDY AGYAPONG', 'KENNEDY1006@GMAI.COM', 0555560810, '3/APRIL/2012', 'CSD1.2', 'MALE', 'PAGA', '17/MAY/2020');

insert into students(STUDENT_ID, STUDENT_NAME, EMAIL, PHONE, DATE_OF_BIRTH, COURSE_ID, GENDER, ADDRESS, REG_DATE) VALUES('CSDM001', 'BISMARK OTU', 'BISMARKOTU1006@GMAI.COM', 0555560810, '3/APRIL/2012', 'CSD1.2', 'MALE', 'BOLGA', '17/MAY/2020');
insert into students(STUDENT_ID, STUDENT_NAME, EMAIL, PHONE, DATE_OF_BIRTH, COURSE_ID, GENDER, ADDRESS, REG_DATE) VALUES('ICDLM045', 'ALFRED CUDJOE', 'ALFREDCUDJOE@GMAI.COM', 0545768689, '20/MAY/1999', 'ICDL3.5', 'FEMALE', 'ACCRA', '17/DECEMBER/2004');
insert into students(STUDENT_ID, STUDENT_NAME, EMAIL, PHONE, DATE_OF_BIRTH, COURSE_ID, GENDER, ADDRESS, REG_DATE) VALUES('NETM127', 'DAVID AVOMAH', 'DAVIDAVOMAH06@GMAI.COM', 0542678940, '13/JUNE/2004', 'NETWORKING8.3', 'MALE', 'TAMALE', '17/MAY/2017');
insert into students(STUDENT_ID, STUDENT_NAME, EMAIL, PHONE, DATE_OF_BIRTH, COURSE_ID, GENDER, ADDRESS, REG_DATE) VALUES('GDM008', 'SHARON ABU-GYANSAH', 'SHARONABU-GYANSAH@GMAI.COM', 0504789834, '30/JULY/2019', 'GRAPH_DESIGN4.4', 'FEMALE', 'WA', '17/JUNE/2005');
insert into students(STUDENT_ID, STUDENT_NAME, EMAIL, PHONE, DATE_OF_BIRTH, COURSE_ID, GENDER, ADDRESS, REG_DATE) VALUES('CYBERMO23', 'MICHAEL ALATEBA', 'MICHAELALATEBA@GMAI.COM', 0209674538, '23/DECEMBER/2012', 'CYBER4.2', 'MALE', 'NAVRONGO', '17/JULY/2019');

INSERT INTO students VALUES('CSDM001', 'BISMARK', 'OTU', 'BISMARKOTU1006@GMAI.COM', 0555560810, '3/APRIL/2012', 'CERTIFICATE IN SOFTWARE DEVELOPMENT', 'MALE', 'BOLGA', '17/MAY/2020');
INSERT INTO students VALUES('ICDLM045', 'ALFRED', 'CUDJOE', 'ALFREDCUDJOE@GMAI.COM', 0545768689, '20/MAY/1999', 'INTERNATIONAL COMPUTER DRIVING LICENCE', 'FEMALE', 'ACCRA', '17/DECEMBER/2004');
INSERT INTO students VALUES('NETM127', 'DAVID', 'AVOMAH', 'DAVIDAVOMAH06@GMAI.COM', 0542678940, '13/JUNE/2004', 'NETWORKING', 'MALE', 'TAMALE', '17/MAY/2017');
INSERT INTO students VALUES('GDM008', 'SHARON', 'ABU-GYANSAH', 'SHARONABU-GYANSAH@GMAI.COM', 0504789834, '30/JULY/2019', 'GRAPH DESIGN', 'FEMALE', 'WA', '17/JUNE/2005');
INSERT INTO students VALUES('CYBERMO23', 'MICHAEL', 'ALATEBA', 'MICHAELALATEBA@GMAI.COM', 0209674538, '23/DECEMBER/2012', 'CYBER SECURITY', 'MALE', 'NAVRONGO', '17/JULY/2019');







--   COURSE  TABLE
create table courses(
COURSE_ID VARCHAR(20),
STUDENT_ID VARCHAR(100) primary key,
COURSE_NAME VARCHAR(100),
COURSE_FEE DECIMAL(10,3),
CONSTRAINT FK_STUDENT_ID FOREIGN KEY(STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID) ON DELETE CASCADE
);



-- ADDING A COLUMN TO TABLE
alter table courses
add (MARKS int(10);



DROP TABLE COURSES;

INSERT INTO COURSES VALUES('CSD1.2','CSDM001','CERTIFICATE IN SOFTWARE DEVELOPMENT',1500.55,'78');
INSERT INTO COURSES VALUES('ICDL3.5','ICDLM045','INTRNATIONAL COMPUTER DRIVING LICENCE', 2750.75, '88');
INSERT INTO COURSES VALUES('NETWORKING8.3','NETM127','NETWORKING', 3578.98, '92');
INSERT INTO COURSES VALUES('CSD1.2','CSDM002','CERTIFICATE IN SOFTWARE DEVELOPMENT',1500.55, '77');
INSERT INTO COURSES VALUES('CYBER4.2','CYBERMO23','CYBER SECURITY',7600.55, '69');




-- SELECTING A SINGLE RECORD FROM COURSE TABLE
SELECT * FROM COURSES
WHERE STUDENT_ID = 'CYBERMO23';







		 -- SELECTING A STUDENT WITH THE MARKS GREATER THAN 80%
   
   select * from students where marks >= 80;
    SELECT * from students, course WHERE students.id = course.id and marks >= 80 and students.id = 1;

SELECT * FROM COURSES;
SELECT * FROM STUDENTS;



--  HOW TO JOIN TWO TABLES OR HOW TO SELECT FROM TWO TABLES

 SELECT * from students, course WHERE students.id = course.id and students.id = 1;
 
 
 
 
 
  --  AN SQL STATEMENT WHICH RETURNS THE RECORDS OF STUDENT NAMES THAT CONTAINS OR HAS LETTER "O"
 SELECT student_name from students WHERE student_name LIKE '%O%';




 --  AN SQL STATEMENT WHICH RETURNS THE RECORDS OF STUDENT NAMES THAT BEGINS WITH THE LETTER "Y"
  SELECT student_name from students WHERE student_name LIKE 'Y%';
  
  
  
   --  AN SQL STATEMENT WHICH RETURNS THE RECORDS OF STUDENT NAMES THAT ENDS WITH THE LETTER "a"
  SELECT student_name from students WHERE student_name LIKE '%a';



